import React from "react";
import "./text.css";

const Howitworkstext = () => {
    return (
        <div>
            <b className="subpoint1">
                <li>If your main page is blank, it is because you need to run the extension first while you are logged in, and then your stats will appear here once you are done. </li>
            </b>
            <b className="subpoint1"><li>
                If you would like to rerun the tests, please refresh the page to
                get new stats afterwards - for now, the page does not
                automatically refresh.</li>
            </b>
            <li>
                <strong>Accuracy: </strong> the number of passed test cases/the
                number of total test cases.{" "}
            </li>
            <li>
                <strong>Static rating:</strong> A global evaluation score for
                the code, rated out of a maximum score of 10.0. The score is
                calculated based on the number of messages (warnings,
                refactorings, errors, etc.) generated by Pylint, weighted by
                their type.{" "}
            </li>
            <li>
                <strong>Coverage rating:</strong>
                The fraction of statements in the code that are covered by the test cases.
            </li>
            <li>
                <strong>Missing Lines:</strong> The lines in the code that are not recahed by the test cases..{" "}
            </li>
            <li>
                <strong>Assertions: </strong>the tested assertion, the result of
                the current run (pass/fail), and the history of the last 5 runs
                of this assertion (pass/fail).{" "}
            </li>
            <li>
                <strong>Static report:</strong> A series of messages categorized
                by their types and a summary of these messages, such as:{" "}
                <li className="subpoint">
                    {" "}
                    [I]nformational messages that Pylint emits (do not
                    contribute to your analysis score)
                </li>
                <li className="subpoint">
                    {" "}
                    [R]efactor for a "good practice" metric violation
                </li>
                <li className="subpoint">
                    [C]onvention for coding standard violation
                </li>
                <li className="subpoint">
                    [W]arning for stylistic problems, or minor programming
                    issues
                </li>
                <li className="subpoint">
                    [E]rror for important programming issues (i.e. most probably
                    bug)
                </li>
                <li className="subpoint">
                    [F]atal for errors which prevented further processing
                </li>
            </li>
            
        </div>
    );
};
export default Howitworkstext;
